### ISSUE TITLE
Issue with input.file generation in with daily run setting

### ISSUE THREAD

**Issue by tsherwen** [BenNewsome/monthly-run#13]
the Monthly run script is having some issues in generating the input files with the  "day" setting.

original input.geos file:
header:
"
Start YYYYMMDD, HHMMSS  : 20150629 000000
End   YYYYMMDD, HHMMSS  : 20150804 000000
"
output settings: 
"
Schedule output for JAN : 3000000000000000000000000000000
Schedule output for FEB : 3000000000000000000000000000
Schedule output for MAR : 3000000000000000000000000000000
Schedule output for APR : 300000000000000000000000000000
Schedule output for MAY : 3000000000000000000333333333333
Schedule output for JUN : 333333333333333333333333333333
Schedule output for JUL : 3333333333333333333333333333333
Schedule output for AUG : 3333333333333333333333333333333
Schedule output for SEP : 333333333000000000000000000000
Schedule output for OCT : 3000000000000000000000000000000
Schedule output for NOV : 300000000000000000000000000000
Schedule output for DEC : 3000000000000000000000000000000
"

For output file for 1st day of run:
header:
"
Start YYYYMMDD, HHMMSS  : 20150629 000000
End   YYYYMMDD, HHMMSS  : 20150630 000000
"
output settings: 
"
Schedule output for JAN : 3000000000000000000000000000000
Schedule output for FEB : 3000000000000000000000000000
0Schedule output for MAR : 3000000000000000000000000000000
Schedule output for APR : 300000000000000000000000000000
Schedule output for MAY : 3000000000000000000333333333303
Schedule output for JUN : 333333333333333333333333333333
Schedule output for JUL : 3333333333333333333333333333303
Schedule output for AUG : 3333333333333333333333333333303
Schedule output for SEP : 333333333000000000000000000000
Schedule output for OCT : 3000000000000000000000000000000
Schedule output for NOV : 300000000000000000000000000000
Schedule output for DEC : 3000000000000000000000000000000
"

**Comment by BenNewsome** [comment]
This was a "Feature" that was unintended. The latest commit should have removed this "Feature" and it should work as expected now.
