### ISSUE TITLE
Selecting the "core32' option from cmd line gui appears to not work

### ISSUE THREAD

**Issue by tsherwen** [BenNewsome/monthly-run#7]
Choosing the "core32" option from the cmd line GUI does not seem to submit the job to the "core32" queue, but instead submits the job to the default "run" queue. 

GUI selection:
"
What queue do you want to go in?
DEFAULT = run :
core32
"
results in PBS queue:
"
?????.earth0      ??201401         ts551             00:00:00 R run  
"

**Comment by bn506** [comment]
Fixed in devel now I think.

If it fails try to see happens if you change DEBUG=True in the script at the start. It should print out "queue name    = ####" where #### is what it should be.

I forgot to push back a temp variable
